### ISSUE TITLE
[Suggestion] Turn automatic conversion ON/OFF by default on browser startup

### ISSUE THREAD

**Issue by Silejonu** [m1l/Everything-Metric-Firefox#2]
It would be very nice to be able to choose whether have the extension is turned on or off by default on Firefox startup.
I end up turning it off whenever I launch Firefox, to avoid including conversions when I copy scripts from the internet. I much prefer having it turned off by default, and turn it on when I need it, but I guess a lot of people prefer it as it is right now.
Having a switch for the default startup state in the add-on preferences would be nice.

**Comment by m1l** [comment]
Ah, that is a weird bug, thanks for reporting. Chrome version is almost exactly the same but if properly restores the addon state when you relaunch it. I'll try to fix it next week. Then you can keep if Off, and just press Alt+M to convert the page without turning on the extension

**Comment by m1l** [comment]
This is now fixed in 3.4

**Comment by mirh** [comment]
Maybe I'm dumb, but the I cannot find this "default off" toggle. 
EDIT: uh, nvm, it's the icon in the nav bar. But that seems more of a global option. Can't we have per-domain preferences?
