### ISSUE TITLE
Negative temperature parsed as positive: `range -10 to -32ºF` → `【-23 to 0°C】`

### ISSUE THREAD

**Issue by qsantos** [m1l/Everything-Metric-Firefox#32]
32°F
-32°F
range -10 to -32ºF

**Comment by m1l** [comment]
Regression bug? It was working in old version that I still run in chrome

**Comment by qsantos** [comment]
This is what I get in Google Chrome with version 3.4 of Everything Metric:

![image](https://github.com/m1l/Everything-Metric-Firefox/assets/8493765/6033e342-d879-44d2-9a50-82dc9179a374)

I have used the git history to try with older versions on Mozilla Firefox, and it indeed used to work in v3.1. The regression comes from commit bfb681ec8c887f215fe99c871252635f89091fa0 (`v3.4`).

It is fixed by commit 1476cb9d27c80e8a5b9b7ebe0cdddacc09bb0a4c from #34.

**Comment by m1l** [comment]
Does it convert these for you when you load extension in firefox and open this page or https://justpaste.it/8yfnp ?
By the way, what are you using for debugging? I used to develop this in Edge and was able to set breakpoints and inspect what values show up, but this time I am doing first FF and I didn't see a way to attach debugger (or at least that's how I remember it, it was long time since I worked on this and with JS)

**Comment by qsantos** [comment]
When I use the official version 3.4, I get `range -10 to -32ºF​【-23 to 0°C】`. However, with the version from the GitHub repository, I do get `【-23 to -36°C】`, as expected, since commit 1476cb9.

I am too lazy to use the debugger, but Firefox does have one in the developer tools, which you can access by hitting F12.

![image](https://github.com/m1l/Everything-Metric-Firefox/assets/8493765/443061e6-f8a6-4f63-a02a-19338768c286)

**Comment by m1l** [comment]
I didn't realize that reloading extension is not enough but I had to remove it and add it again this time to run the latest code.
Thanks! I'll try the debugging this way.

**Comment by qsantos** [comment]
Ah, I see! I use [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/), which start a new profile, and lets me test without having to pack or install the extension. It also reloads the extension automatically whenever there is a change!
