### ISSUE TITLE
`1 ft 2 inches` → `【0,7 m】es`

### ISSUE THREAD

**Issue by qsantos** [m1l/Everything-Metric-Firefox#35]
This pattern is affected by #27, but there is a second bug: “inches” is split, with only “inch” being use as the unit, and “es” being kept as-is.

1 ft 2 inches

**Comment by m1l** [comment]
Fixed with https://github.com/m1l/Everything-Metric-Firefox/commit/7bf3d64adf65732f4b9571d6d275799802e4b22b

**Comment by qsantos** [comment]
Thanks!
