### ISSUE TITLE
„äriseadustiku §-s 60”​【1,5 m】should not result in conversion

### ISSUE THREAD

**Issue by kaidoloor** [m1l/Everything-Metric-Firefox#45]
It seems that if a quote in "" (or „”) ends with a number, the extension considers this as inch. Which is not correct. How to fix that? In what file? How to test?

**Comment by m1l** [comment]
Go to addon options, and uncheck "Convert Improper symbols for foot and inch"

**Comment by mirh** [comment]
I still feel like we have a bug here. 
It's one thing to "not be really picky" and detect `''` (twice *0x27*) or `"` (0x22) as equivalent to the most proper `″` (*U+2033*). 
It's another to bunch together `“` (*0x201C*) or `”` (*0x201D*) like here, symbols that even they aren't being used by cultures different from the only one still clinching to the FFF system, you'd be absolutely hard pressed to use accidentally. Let alone for units of measure.
