### ISSUE TITLE
Weirdness with "draft 01"

### ISSUE THREAD

**Issue by redfast00** [m1l/Everything-Metric-Firefox#6]
See the comment at https://bugzilla.mozilla.org/show_bug.cgi?id=1667801#c28

**Comment by milos12345** [comment]
I don't see anything familiar there. What am I supposed to see?

**Comment by m1l** [comment]
I don't see anything familiar there. What am I supposed to see?

**Comment by redfast00** [comment]
For me the comment by `uBlock-user` reads
```
(In reply to Masatoshi Kimura [:emk] from comment #27)

    I guess ECH will not work until bug 1678079 is fixed.

Can you confirm if the CloudFlare team is still running their draft 01 on their side ? From what I read on GitHub, back in 2019, it was dr​【NaN m】deed.
```

Here `dr​【NaN m】deed` is shown instead of `draft 01 indeed`. This happens with Firefox.

**Comment by m1l** [comment]
Got it. I'll add it to the to do list for the next version
